-- Plain SQL only. This runs against H2 locally and Postgres in production, so no
-- vendor-specific types and no vendor-specific syntax.

create table bookmark (
    id         bigint generated by default as identity primary key,
    url        varchar(2048) not null,
    title      varchar(200)  not null,
    notes      varchar(2000),
    favourite  boolean       not null default false,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

-- Tags get their own table rather than a comma-separated column, so a tag filter is an
-- indexed equality match instead of a leading-wildcard LIKE that can never use an index.
create table bookmark_tag (
    bookmark_id bigint      not null references bookmark (id) on delete cascade,
    tag         varchar(50) not null,
    primary key (bookmark_id, tag)
);

-- Supports the default newest-first list order. The id is part of the index because it is
-- part of the sort: without a unique final key, rows sharing a created_at can appear on two
-- pages or on none.
--
-- Both columns are descending because a btree can only be read forwards or backwards, never
-- one column each way. Every ORDER BY in the code therefore ends `created_at desc, id desc` —
-- mixing the directions still returns the right rows, it just sorts them by hand.
create index idx_bookmark_created_at on bookmark (created_at desc, id desc);

-- Supports filtering by tag. The primary key above is ordered (bookmark_id, tag), so it
-- cannot serve a lookup that starts from the tag.
create index idx_bookmark_tag_tag on bookmark_tag (tag);
